export const HANDLE_LOGIN = 'HANDLE_LOGIN';
export const HANDLE_SIGNUP = 'HANDLE_SIGNUP';
export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';

export const SET_USER = 'SET_USER';

// HOME
export const GET_CURRENT_LOCATION = 'GET_CURRENT_LOCATION';

// TOW BOOKING
export const PUSH_TO_TOW_REQUESTS = 'PUSH_TO_TOW_REQUESTS';
export const GET_TOW_BOOKINGS = 'GET_TOW_BOOKINGS';
export const GET_TOW_BOOKING = 'GET_TOW_BOOKINGS';
export const REMOVE_TOW_REQUEST = 'REMOVE_TOW_REQUEST';
export const ADD_TOW_REQUEST = 'ADD_TOW_REQUEST';
